sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t acrisan420/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true acrisan420/docker-react npm run test
